insert into book (id, isbn, name, owner, publisher) values (1, 229, 'Waved albatross', 'Ches Antunes', 'Feednation');
insert into book (id, isbn, name, owner, publisher) values (2, 674, 'Topi', 'Gayla Farthin', 'Meembee');
insert into book (id, isbn, name, owner, publisher) values (3, 70, 'Colobus, magistrate black', 'Leon Hinsche', 'Yata');
insert into book (id, isbn, name, owner, publisher) values (4, 799, 'Porcupine, tree', 'Fayth Alcalde', 'Janyx');
insert into book (id, isbn, name, owner, publisher) values (5, 217, 'Indian porcupine', 'Anson Fortun', 'Shufflebeat');
insert into book (id, isbn, name, owner, publisher) values (6, 784, 'Stork, white', 'Julissa Phillott', 'Eayo');
insert into book (id, isbn, name, owner, publisher) values (7, 474, 'Springbok', 'Kip Ridings', 'Wikibox');
insert into book (id, isbn, name, owner, publisher) values (8, 499, 'African jacana', 'Helge Pidon', 'Jazzy');
insert into book (id, isbn, name, owner, publisher) values (9, 157, 'Tortoise, asian foreset', 'Renaud Beauchamp', 'Cogidoo');
insert into book (id, isbn, name, owner, publisher) values (10, 107, 'Monkey, black spider', 'Rudy Dullingham', 'Ailane');
insert into book (id, isbn, name, owner, publisher) values (11, 414, 'Hornbill, red-billed', 'Rici Elie', 'Kwinu');
insert into book (id, isbn, name, owner, publisher) values (12, 829, 'Jackal, asiatic', 'Mariska Farran', 'Eadel');
insert into book (id, isbn, name, owner, publisher) values (13, 888, 'Stilt, black-winged', 'Laurens Martinyuk', 'Tavu');
insert into book (id, isbn, name, owner, publisher) values (14, 70, 'Egyptian viper', 'Tamarra Godmar', 'Yakidoo');
insert into book (id, isbn, name, owner, publisher) values (15, 579, 'Red kangaroo', 'Rhody Kleinerman', 'Thoughtmix');
insert into book (id, isbn, name, owner, publisher) values (16, 781, 'Palm squirrel', 'Ivie Dorcey', 'Photospace');
insert into book (id, isbn, name, owner, publisher) values (17, 675, 'Japanese macaque', 'Delmore Lynagh', 'Kanoodle');
insert into book (id, isbn, name, owner, publisher) values (18, 872, 'Swan, black', 'Drusie Drewes', 'Abatz');
insert into book (id, isbn, name, owner, publisher) values (19, 97, 'Neotropic cormorant', 'Ardenia Aish', 'Cogibox');
insert into book (id, isbn, name, owner, publisher) values (20, 360, 'Possum, common brushtail', 'Jo Pert', 'Yakidoo');
insert into book (id, isbn, name, owner, publisher) values (21, 883, 'Red-capped cardinal', 'Jenna Ulyet', 'Fiveclub');
insert into book (id, isbn, name, owner, publisher) values (22, 44, 'Pademelon, red-legged', 'Cam Tireman', 'Thoughtstorm');
insert into book (id, isbn, name, owner, publisher) values (23, 211, 'Pied kingfisher', 'Micheal Marchington', 'Yata');
insert into book (id, isbn, name, owner, publisher) values (24, 517, 'Steenbuck', 'Wini Bremmell', 'Bluejam');
insert into book (id, isbn, name, owner, publisher) values (25, 783, 'Long-tailed jaeger', 'Thorpe Gallichiccio', 'Camimbo');
insert into book (id, isbn, name, owner, publisher) values (26, 573, 'Pied avocet', 'Constantine Cawthorn', 'Skidoo');
insert into book (id, isbn, name, owner, publisher) values (27, 524, 'Porcupine, north american', 'Remus Mityashev', 'Wordware');
insert into book (id, isbn, name, owner, publisher) values (28, 1000, 'Heron, gray', 'Hillyer Piotrowski', 'Skivee');
insert into book (id, isbn, name, owner, publisher) values (29, 260, 'Eastern cottontail rabbit', 'Miran Mc Elory', 'Feednation');
insert into book (id, isbn, name, owner, publisher) values (30, 728, 'Badger, european', 'Belicia Gerardeaux', 'Gabcube');
insert into book (id, isbn, name, owner, publisher) values (31, 9, 'European spoonbill', 'Felipa Kleen', 'Oyonder');
insert into book (id, isbn, name, owner, publisher) values (32, 242, 'Bee-eater, carmine', 'Claudetta Tranckle', 'Thoughtstorm');
insert into book (id, isbn, name, owner, publisher) values (33, 945, 'Lion, steller''s sea', 'Joellen Sturdy', 'Chatterpoint');
insert into book (id, isbn, name, owner, publisher) values (34, 8, 'Malachite kingfisher', 'Gabriel Twidle', 'Photobean');
insert into book (id, isbn, name, owner, publisher) values (35, 421, 'Squirrel, eurasian red', 'Caryn Klassmann', 'Trudoo');
insert into book (id, isbn, name, owner, publisher) values (36, 352, 'Bandicoot, long-nosed', 'Wilden Gepheart', 'Oyoba');
insert into book (id, isbn, name, owner, publisher) values (37, 463, 'Black-backed magpie', 'Benny Fontanet', 'Avavee');
insert into book (id, isbn, name, owner, publisher) values (38, 910, 'Spoonbill, european', 'Doris Michael', 'InnoZ');
insert into book (id, isbn, name, owner, publisher) values (39, 726, 'Otter, african clawless', 'Gottfried McKern', 'Trudeo');
insert into book (id, isbn, name, owner, publisher) values (40, 761, 'Great egret', 'Marlin Mosey', 'Layo');
insert into book (id, isbn, name, owner, publisher) values (41, 639, 'Brown capuchin', 'Eula Dekeyser', 'Quaxo');
insert into book (id, isbn, name, owner, publisher) values (42, 512, 'South American meadowlark (unidentified)', 'Humphrey Dudson', 'Dabjam');
insert into book (id, isbn, name, owner, publisher) values (43, 616, 'Shark, blue', 'Lyssa Lapsley', 'Wikibox');
insert into book (id, isbn, name, owner, publisher) values (44, 780, 'Turtle, long-necked', 'Cory Jarred', 'Photobug');
insert into book (id, isbn, name, owner, publisher) values (45, 51, 'Thrasher, curve-billed', 'Gerianna Roarty', 'Brainverse');
insert into book (id, isbn, name, owner, publisher) values (46, 871, 'Common brushtail possum', 'Marget Metzel', 'Flashset');
insert into book (id, isbn, name, owner, publisher) values (47, 504, 'Cereopsis goose', 'Geraldine McBratney', 'Kaymbo');
insert into book (id, isbn, name, owner, publisher) values (48, 249, 'Fat-tailed dunnart', 'Cecily Sallows', 'Brightdog');
insert into book (id, isbn, name, owner, publisher) values (49, 977, 'Snake, eastern indigo', 'Kareem Mullins', 'Flashpoint');
insert into book (id, isbn, name, owner, publisher) values (50, 844, 'Black kite', 'Lindi Ewells', 'Kanoodle');
